services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_DB=quizzo